### ISSUE TITLE
[org-mode][babel]code block of JavaScript compiling error

### ISSUE THREAD

**Issue by wxie2017** [wxie2017/C0D3#1]
Emacs version: 
GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20) of 2020-05-17, modified by Debian
Org-mode version: 
Org mode version 9.1.9 (release_9.1.9-65-g5e4542 @ /usr/share/emacs/26.3/lisp/org/)

sample code block:
'''
#+BEGIN_SRC js
cosole.log("hello")
#+END_SRC
'''
Error:
'''
/tmp/babel-u4ecWm/js-script-YO00zj:1
require('sys').print(require('sys').inspect(function(){
               ^
TypeError: require(...).print is not a function
    at Object.<anonymous> (/tmp/babel-u4ecWm/js-script-YO00zj:1:16)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
'''

**Comment by wxie2017** [comment]
Solved with
GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20)
under GUIX 1.1.0

**Comment by wxie2017** [comment]
close this issue.
